<div class="container">
    <?php        
        if (!$this->ok) {?>
    <form class="form-signin" method="POST" action="<?= $this->baseUrl() . '/logar' ?>">
                <h2 class="form-signin-heading">Please sign in</h2>
                <label for="inputEmail" class="sr-only">Email address</label>
                <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Email address" required autofocus>
                <label for="inputPassword" class="sr-only">Password</label>
                <input type="password" id="inputPassword" name="senha" class="form-control" placeholder="Password" required>

                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            </form>
            
    <p> <?= $this->mgm; ?> </p>
    
    <?php } else echo '<h1>Página inicial do ' . $this->result->nome . ' </h1>';?>