<div class="container">
    <div id="mensagens"></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <?php if($this->role){ ?>                
                <th>ID</th> <?php } ?>
                <th>NOME</th>
                <th>EMAIL</th>
                <?php if($this->role){ ?>
                <th>ROLE</th> <?php } ?>
                <?php if($this->role){ ?>
                <th>STATUS</th> <?php } ?> 
                <th>OPÇÕES</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->lista as $rows) {
            ?>
                <tr>
                     <?php if($this->role){ ?>  <td><?php echo $rows->getId(); ?> </td> <?php } ?>
                    <td><?php echo $rows->getNome(); ?> </td>
                    <td><?php echo $rows->getEmail(); ?> </td>
                    <?php if($this->role){ ?>  <td><?php echo $rows->getRole(); ?> </td> <?php } ?>
                    <?php if($this->role){ ?>  <td><?php echo $rows->getStatus(); ?> </td> <?php } ?>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary ">Opções</button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?= $this->baseUrl() . '/atualizar/index?id=' . $rows->getId(); ?>">Atualizar</a></li>
                                <?php
                                if ($this->role) {
                                ?>
                                    <li><a onclick="remover(<?php echo $rows->getId(); ?>, this);">Remover</a></li>
                                    
                                <?php } ?>
                            </ul>
                        </div>
                    </td>
                    
                </tr>
            <?php } ?>

        </tbody>
    </table>

