<div class="container">
    <div id="mensagens"></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>NOME</th>
                <th>EMAIL</th>
                <th>SENHA</th>
                <th>OPÇÕES</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            $auth = Zend_Auth::getInstance();
            $result = $auth->getStorage()->read();

            foreach ($this->lista as $rows) {
            ?>
                <tr>
                    <td><?php echo $rows->getId(); ?> </td>
                    <td><?php echo $rows->getNome(); ?> </td>
                    <td><?php echo $rows->getEmail(); ?> </td>
                    <td><?php echo $rows->getSenha(); ?> </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary ">Opções</button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?= $this->baseUrl() . '/atualizar/index?id=' . $rows->getId(); ?>">Atualizar</a></li>
                                <?php
                                if ($result->role == 'admin') {
                                ?>
                                    <li><a onclick="remover(<?php echo $rows->getId(); ?>, this);">Remover</a></li>
                                    
                                <?php } ?>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php } ?>

        </tbody>
    </table>

