<footer class="footer">
    <div class="container-fluid">
        <p class="text-muted">&copy; My first Zend Project!.</p>
    </div>
</footer>

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Cadastro de Novo Usuario</h4>
            </div>
            <form role="form" action="<?= $this->baseURL() . '/cadastrar' ?>" method="POST" name="frmClientes" return false>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Nome</label>
                        <input type="text" name="nome" id="nome" class="form-control" placeholder="Name" required>
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="email" class="form-control" placeholder="Email address" required>
                    </div>

                    <div class="form-group">
                        <label>Senha</label>
                        <input type="password" name="senha" class="form-control" placeholder="Password" required>
                    </div>

                    <button type="submit" class="btn btn-success btn-lg">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Registrar
                    </button>

                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-circle" data-dismiss="modal"><i class="fa fa-times"></i>x</button>
            </div>
        </div>
    </div>
</div>
