<div class="container">
    <!-- Static navbar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">                
                <a class="navbar-brand" href="#">Zend Project</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?= $this->baseURL() . '/index' ?>">Home</a></li>
                    <li><a href="<?= $this->baseURL() . '/cadastrar' ?>">Cadastro</a></li>
                    <li><a href="<?= $this->baseURL() . '/listar' ?>">Listar Dados</a></li>
                </ul>            
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>