
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Zend Project</title>

        <!-- Bootstrap core CSS -->
        <link href="<?= $this->baseURL() . '/css/bootstrap.min.css' ?>" rel="stylesheet">
        
        <link href="<?= $this->baseURL() . '/css/signin.css' ?>" rel="stylesheet">
        <link href="<?= $this->baseURL() . '/css/sticky-footer.css' ?>" rel="stylesheet">              
    </head>

    <body>

        <?php echo $this->render("header.phtml"); ?>
        <div class="jumbotron"><?php echo $this->layout()->content; ?> </div>

    </div> <!-- /container -->
    <?php echo $this->render("footer.phtml"); ?>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>        
    <!--<script src="js/bootstrap.min.js"></script>-->
    <script src="<?= $this->baseURL() . '/js/bootstrap.min.js' ?>"></script>
    <script src="<?= $this->baseURL() . '/js/jquery.js' ?>"></script>
    <script src="<?= $this->baseURL() . '/js/Modal.js' ?>"></script>



</body>
</html>

